# This is a basic workflow to help you get started with Actions

name: build

on:
  schedule:
    - cron: '0 0 * * *' # 每天0点推送
  #Allows you to run this workflow
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      
    - name: Update README
      run: |
        echo "test" >> README.md
        git config --global user.name "Your Name"
        git config --global user.email "your.email@example.com"
        git add .
        git commit -m "Update"
        git push
